### ISSUE TITLE
미니 프로젝트 결과 산출물 - Streamlit 시연 영상

### ISSUE THREAD

**Issue by yejinlee99** [pladata-encore/DA36_mini2_Dionysus#10]
## 🌈 Success criteria

1. streamlit app 시연 영상 촬영 및 유튜브 업로드하기

## 👷 To-do

- [x] streamlit app 시연 영상 촬영 5분
- [ ] 영상에 자막 넣기
- [ ] 영상 유튜브에 업로드
