### ISSUE TITLE
Streamlit App - 와린이를 위한 와인 추천

### ISSUE THREAD

**Issue by yejinlee99** [pladata-encore/DA36_mini2_Dionysus#16]
## 🌈 Success criteria

1. 와인 추천해주는 Streamlit App 을 생성한다.
2. 와인 추천 시스템 첫 화면에는 아래 세가지 카테고리가 나와야 한다. 
    - 와린이를 위한 와인 추천 (*와린이 : 와인 + 어린이를 합친 합성어)
3. 각 카테고리의 결과로 추천 와인 Best 3와 비추천 와인 Worst 3를 보여줘야한다.
4. 각 와인을 추천해줄 때  와인 이름, 가격, 나라, 포도 품질, 와이너리를 보여줘야한다.  

## 👷 To-do

- [x] Streamlit App에 어떻게 보여줄지 구상하기
- [x] streamlit 에 적용시킬 모델.py 파일 생성하기
- [x] 와린이를 위한 와인 추천 시스템 구현하기
- [x] Best 3, Worst 3 추천하기
