### ISSUE TITLE
컨텐츠 기반 <맛잘알을 위한 와인 추천> 구현

### ISSUE THREAD

**Issue by haeb98** [pladata-encore/DA36_mini2_Dionysus#37]
## 🌈 Success criteria

1. <맛잘알을 위한 와인 추천> 시스템을 컨텐츠 기반 추천 시스템으로 구현한다
2.

## 👷 To-do

- [x] 'foods' 컬럼 CountVectorizer 파라미터 최적화
- [x] cosine similarity를 기준으로 Best 10 선정
- [x] Weighted ratings 기준으로 정렬
- [x] price filter 추가

**Comment by haeb98** [comment]
Commit: 2b8b7a1

**Comment by haeb98** [comment]
Commit: 40fdfff
