### ISSUE TITLE
회귀 기반 추천 시스템 - 와린이에게 취향 물어보기

### ISSUE THREAD

**Issue by yejinlee99** [pladata-encore/DA36_mini2_Dionysus#5]
## 🌈 Success criteria

1. 와린이는 와인에 대해 잘 모릅니다.
2. 와린이에게 와인을 추천해 주기 위해서는 보다 심플하게 취향을 물어봐야 합니다.
3. 아래의 표에 나와있는 질문을 토대로 선택지를 작성하세요.

| 선택 | 질문 | 선택지 |
|------|------|--------|
| **선택1** | 더 선호하시는 것은 무엇입니까? | 1) 고기  2) 생선  3) 채소 |
| **선택2** | 더 선호하시는 것은 무엇입니까? | 1) 트로피칼  2) 시트러스  3) 베리  4) 향신료 |
| **선택3** | 더 선호하시는 것은 무엇입니까?| 1) 장미꽃  2) 제비꽃  3) 백합  4) 나무 |
| **선택4** | 더 선호하시는 것은 무엇입니까? | 1) 달콤한 초콜릿  2) 카카오 50%  3) 카카오 100% |
| **선택5** | 어떤 김치를 더 좋아하세요? | 1) 묵은지  2) 신김치  3) 조금 익은 김치 |
| **선택6** | 좋아하는 커피 종류를 알려주세요. | 1) 라떼  2) 에스프레소  3) 아메리카노 |
| **선택7** | 홍차의 떫은 맛에 더 익숙한가요? | 1) 진하게 우려낸  2) 적당히 우려낸  3) 연하게 우려낸 |

## 👷 To-do

- [x] 선택지에 들어갈 단어를 리뷰에서 찾은 단어들로 구성(매칭)하기
- [x] 선택지
- [x] 와린이가 한 선택(숫자)를 단어로 변경하기
- [x] 텍스트를 조합하여 새로운 리뷰를 만들기
- [x] 새로운 리뷰와 유사한 리뷰를 찾아  좋아할것 같은 와인 5개 추천하기
- [x] 싫어할것 같은 와인 5개 추천하기
